DELETE FROM examinations;
DELETE FROM accounts;
DELETE FROM options;
DELETE FROM account_examinations;
DELETE FROM account_roles;
DELETE FROM examination_options;
DELETE FROM examination_results;
DELETE FROM questions;
DELETE FROM users;