DELETE FROM examinations;
DELETE FROM accounts;
DELETE FROM answers;
DELETE FROM account_examinations;
DELETE FROM account_roles;
DELETE FROM examination_answers;
DELETE FROM examination_results;
DELETE FROM questions;
DELETE FROM users;